name: cd

on:
  workflow_dispatch:
  push:
    tags: [ 'v-*' ]

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -ldflags="-w -s" -o main.out ./src/main.go
      - name: Chmod
        run: chmod +x main.out
      - name: Run
        run: ./main.out
